export interface IImage {
            id: string,
            title: string,
            description: string,
            datetime: number,
            type: string,
            animated: boolean,
            width: number,
            height: number,
            size: number,
            views: number,
            bandwidth: number,
            vote: string,
            favorite: boolean,
            nsfw: string,
            section: string,
            account_url: string,
            account_id: string,
            is_ad: boolean,
            in_most_viral: boolean,
            has_sound: boolean,
            tags: [],
            ad_type: number,
            ad_url: string ,
            edited: number,
            in_gallery: boolean,
            link:string,
            comment_count: number,
            favorite_count: number,
            ups: number,
            downs: number,
            poinboots: number,
            score: number
        }